# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FirebaseApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

  target 'FirebaseAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FirebaseApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FirebaseApp-tvOS

  target 'FirebaseApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
