# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ChatApp' do
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
end