# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ChatApp' do
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end